---
abstract: 'Asynchronous redis client using hiredis and EV'
author:
  - 'Daisuke Murase <typester@cpan.org>'
build_requires:
  ExtUtils::CBuilder: 0
  Module::Build::Pluggable::XSUtil: 0.01
  Test::Deep: 0
  Test::More: 0.98
  Test::RedisServer: 0.12
  Test::TCP: 1.18
configure_requires:
  ExtUtils::ParseXS: 2.21
  Module::Build: 0.40
  Module::Build::Pluggable::XSUtil: 0.01
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: EV-Hiredis
no_index:
  directory:
    - deps
provides:
  EV::Hiredis:
    file: lib/EV/Hiredis.pm
    version: 0.01
requires:
  EV: 4.11
  XSLoader: 0.02
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
